# Generated by Django 2.1.2 on 2018-10-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missioncontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
