# Generated by Django 2.1.2 on 2018-10-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missioncontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('IN_PROGRESS', 'IN_PROGRESS'), ('REVIEW', 'REVIEW'), ('DONE', 'DONE')], default='PENDING', max_length=20),
        ),
    ]
