version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/python:3.6-stretch-browsers # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Install Node
          command: |
            pushd /tmp
            wget https://nodejs.org/download/release/v8.11.3/node-v8.11.3-linux-x64.tar.gz
            tar -xf node-v8.11.3-linux-x64.tar.gz
            sudo cp -r node-v8.11.3-linux-x64 /opt/
            sudo ln -sf /opt/node-v8.11.3-linux-x64/bin/node /usr/local/bin/
            sudo ln -sf /opt/node-v8.11.3-linux-x64/bin/npm /usr/local/bin/
            node --version
            npm --version
            popd
      - run:
          name: Build Frontend
          command: |
            cd frontend
            npm install
            npm run build
      - run:
          name: Deploy to S3
          command: |
            sudo pip install awscli
            aws s3 sync frontend/dist/ s3://mission-plan-dev
            # gzip bundle and upload to S3 without the .gz extension, with content-encoding 'gzip'
            # we work with wildcards so as to not interfere with hashes used for cache busting
            gzip frontend/dist/bundle*.js
            BUNDLE_FILENAME=$(basename $(ls frontend/dist/bundle*.js.gz))
            aws s3 cp --content-encoding gzip frontend/dist/$BUNDLE_FILENAME s3://mission-plan-dev/$(basename $BUNDLE_FILENAME .gz)
