version: 2
jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - run:
          name: Install Node
          command: |
            wget https://nodejs.org/download/release/v8.11.3/node-v8.11.3-linux-x64.tar.gz
            tar -xf node-v8.11.3-linux-x64.tar.gz
            sudo cp -r node-v8.11.3-linux-x64 /opt/
            sudo ln -s /opt/node-v8.11.3-linux-x64/bin/node /usr/local/bin/
            sudo ln -s /opt/node-v8.11.3-linux-x64/bin/npm /usr/local/bin/
            node --version
            npm --version
      - checkout # check out the code in the project directory
      - run:
          name: Build Frontend
          command: |
            cd frontend
            npm install
            npm run build
      - run:
          name: Deploy to S3
          command: aws s3 sync frontend/dist/ s3://mission-plan-dev
